In [7]:
import pandas as pd

In [3]:
df = pd.read_excel('agendamento_202606121322_formatado.xlsx')
display(df.head())

,Código do agendamento,Data do agendamento,Hora início,Hora fim,CPF do assistido,Nome do assistido,Organização,Serviço,Local,Responsável pelo agendamento,Criado por,Data de criação,Atualizado por,Data de atualização,Agendamento realizado,Tipo,Status
0,46619,2021-04-09,09:00,09:40,301.568.311-04,SUYAN SANTANNA BATISTA DE MATTOS,SINPRO/DF,NaN,NaN,FERNANDA NASCIMENTO SILVEIRA VARGAS,NaN,2021-04-08 16:09:48,NaN,2021-04-09 09:49:37,Sim,Online,Válido
1,46620,2021-04-09,09:40,10:00,143.492.051-87,RAIMUNDO NONATO NEVES DE MENEZES,SINPRO/DF,NaN,NaN,MARINA MENEZES VINHAES,NaN,2021-04-08 16:59:43,NaN,2021-04-09 09:50:35,Sim,Online,Válido
2,46621,2021-04-09,11:20,11:40,428.329.773-91,LEILA LOPES DA SILVA MOTA CAMPELO,SINPRO/DF,NaN,NaN,MARINA MENEZES VINHAES,NaN,2021-04-09 10:11:09,NaN,2021-04-09 11:26:35,Sim,Online,Válido
3,46622,2021-04-09,16:00,16:20,555.355.006-82,RITA DE CASSIA DE OLIVEIRA SILVA,SINPRO/DF,NaN,NaN,MARINA MENEZES VINHAES,NaN,2021-04-09 14:37:11,NaN,2021-04-09 16:10:31,Sim,Online,Válido
4,46623,2021-04-09,16:20,16:40,390.680.219-15,DAVID LANGRAFE,SINPRO/DF,NaN,NaN,MARINA MENEZES VINHAES,NaN,2021-04-09 14:52:53,NaN,2021-04-09 16:31:44,Sim,Online,Válido

In [4]:
df.to_json('atendimentos.json', orient='records', indent=4)

C:\Users\guilh\AppData\Local\Temp\ipykernel_8988\384697645.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json('atendimentos.json', orient='records', indent=4)

In [5]:
json_file = pd.read_json('atendimentos.json')
display(json_file.head())

,Código do agendamento,Data do agendamento,Hora início,Hora fim,CPF do assistido,Nome do assistido,Organização,Serviço,Local,Responsável pelo agendamento,Criado por,Data de criação,Atualizado por,Data de atualização,Agendamento realizado,Tipo,Status
0,46619,1617926400000,09:00,09:40,301.568.311-04,SUYAN SANTANNA BATISTA DE MATTOS,SINPRO/DF,NaN,NaN,FERNANDA NASCIMENTO SILVEIRA VARGAS,NaN,1617898188000,NaN,1.617962e+12,Sim,Online,Válido
1,46620,1617926400000,09:40,10:00,143.492.051-87,RAIMUNDO NONATO NEVES DE MENEZES,SINPRO/DF,NaN,NaN,MARINA MENEZES VINHAES,NaN,1617901183000,NaN,1.617962e+12,Sim,Online,Válido
2,46621,1617926400000,11:20,11:40,428.329.773-91,LEILA LOPES DA SILVA MOTA CAMPELO,SINPRO/DF,NaN,NaN,MARINA MENEZES VINHAES,NaN,1617963069000,NaN,1.617968e+12,Sim,Online,Válido
3,46622,1617926400000,16:00,16:20,555.355.006-82,RITA DE CASSIA DE OLIVEIRA SILVA,SINPRO/DF,NaN,NaN,MARINA MENEZES VINHAES,NaN,1617979031000,NaN,1.617985e+12,Sim,Online,Válido
4,46623,1617926400000,16:20,16:40,390.680.219-15,DAVID LANGRAFE,SINPRO/DF,NaN,NaN,MARINA MENEZES VINHAES,NaN,1617979973000,NaN,1.617986e+12,Sim,Online,Válido